### ISSUE TITLE
Need Mihawk platform file in skiboot for op930 branch

### ISSUE THREAD

**Issue by chcyjoy** [ibm-op-release/op-build#593]
Looks like the pull-request for Mihawk config files is merged and closed. ibm-op-release/op-build/(#592)

Now we need Mihawk platform file pick-up from upstream. open-power/skiboot@9570730

From ibm taipei AE's notice, it sounds like skiboot team will backport Mihawk related patches to skiboot-6.3.x branch. so we would like to create this issue to track the status. Since our release plan is on 8/5 and 8/19, we really need to catch up the schedule.

-- Joy Chu (PNOR engineer at Wistron)

**Comment by HankChang** [comment]
The Mihawk related upstream commit open-power/skiboot@9570730 is backported into skiboot-6.3.x branch here:  https://github.com/open-power/skiboot/commit/8757b12d44ebafa70eb9d8af8ffb39b1ed4872e5

=> So looks like it's just waiting for the BR2_SKIBOOT_VERSION being updated in release-op930 branch.

-- Hank

**Comment by hegdevasant** [comment]
Here you go : https://github.com/ibm-op-release/op-build/pull/594

-Vasant

**Comment by chcyjoy** [comment]
@hegdevasant is there any plan or schedule to merge the PR #594? We hope to use the op930 branch for our second release (8/19) this month.

-- Joy Chu

**Comment by hegdevasant** [comment]
> @hegdevasant is there any plan or schedule to merge the PR #594? We hope to use the op930 branch for our second release (8/19) this month.
> 
> -- Joy Chu

I don't have commit access. Someone with commit access should pull that PR.


-Vasant

**Comment by chcyjoy** [comment]
> > @hegdevasant is there any plan or schedule to merge the PR #594? We hope to use the op930 branch for our second release (8/19) this month.
> > -- Joy Chu
> 
> I don't have commit access. Someone with commit access should pull that PR.
> 
> -Vasant

Do you know anyone with  commit access can help us to speed up this PR?

--joy chu

**Comment by dcrowell77** [comment]
@klauskiwi ?

**Comment by chcyjoy** [comment]
@dcrowell77 @klauskiwi would you please help us find someone to handle this PR?
--joy chu

**Comment by HankChang** [comment]
@chcyjoy   FYI -- the PR has been merged, so this issue could be closed.

-- also, we've created a new op940 branch with skiboot-v6.4* which already included the Mihawk platform file: 
https://github.com/ibm-op-release/op-build/blob/release-op940/openpower/package/skiboot/Config.in
https://github.com/open-power/skiboot/commits/v6.4-15-gdab352eecb1d

Thanks, 
--Hank
