### ISSUE TITLE
Some updates for Mihawk in upstream are really needed in op940

### ISSUE THREAD

**Issue by chcyjoy** [ibm-op-release/op-build#670]
Currently we need some features to be merged or added in op940. Our due date is 12/10. We hope to have these updates as soon as possible.

1. skiboot update or backport to v6.5.x
There are two commits we need:
open-power/skiboot@52952ac
open-power/skiboot@425340b
2. (Merged) kernel size reviewing
op-build/PR/#664
3. (Merged) mihawk config merged
op-build/PR/#658
(This commit was merged upstream open-power/op-build@f9c0ed5)
4. (Merged) Petitboot updates for RHEL8/Openshift support [Nice-to-Have for GA1]
Patches are now upstream:
open-power/petitboot@057dce2
(just mirror the @jk-ozlabs msg from internal commit/bugzillia)

**Comment by HankChang** [comment]
For 2. kernel size reviewing --> Upstream merged: https://github.com/open-power/op-build/pull/3283

**Comment by klauskiwi** [comment]
>     1. skiboot update or backport to v6.5.x
>        There are two commits we need:
>        [open-power/skiboot@52952ac](https://github.com/open-power/skiboot/commit/52952ac)
>        [open-power/skiboot@425340b](https://github.com/open-power/skiboot/commit/425340b)

Is there a PR to release-op940 for these? if you are cherry-picking, make sure you use "-x" to mention the original upstream commit.

**Comment by HankChang** [comment]
Hi @hegdevasant @wghoffa 
There are two upstreamed skiboot commits that Mihawk needs. Could you please help @chcyjoy to take a look?

> skiboot update or backport to v6.5.x
> There are two commits we need:
> open-power/skiboot@52952ac
> open-power/skiboot@425340b

Now Wistron Joy is trying to git-send/backport these patches to skiboot v6.5.x branch for the next op940 build.

Many thanks!
-Hank

**Comment by HankChang** [comment]
@chcyjoy FYI - Based on the HOWTO submit to stable rules: 
https://github.com/open-power/skiboot/blob/master/doc/process/stable-skiboot-rules.rst

Looks like you would need to add the following two lines before your `Signed-off-by` line in the *.patch:
> Cc: skiboot-stable@lists.ozlabs.org #6.5.x 52952ac platform/mihawk: Add system VPD EEPROM to I2C bus
> Cc: skiboot-stable@lists.ozlabs.org #6.5.x 425340b platform/mihawk: Detect old system compatible string

**Comment by HankChang** [comment]
@chcyjoy  FYI - items (2). and (3). were merged:
https://github.com/ibm-op-release/op-build/pull/664
https://github.com/ibm-op-release/op-build/pull/658

The item (1) for the vpd device-tree fix in skiboot upstream is still waiting for reviewing/backporting... 
@hegdevasant @wghoffa @oohal  -- Could you please help Wistron Joy to take a look?  

Look like Joy did send the patches out to <skiboot-stable@lists.ozlabs.org>, but not sure whether the related maintainer received it or not. Kindly let us know if there is any actions need to do. Thank you! 
(still couldn't find any threads related to their submitted patches...)
https://patchwork.ozlabs.org/project/skiboot/list/
https://lists.ozlabs.org/pipermail/skiboot/

> 1. skiboot update or backport to v6.5.x
> There are two commits we need:
> open-power/skiboot@52952ac
> open-power/skiboot@425340b

-Hank

**Comment by HankChang** [comment]
@chcyjoy , let's add one more tracking item here:
4.  Petitboot updates for RHEL8/Openshift support [Nice-to-Have for GA1]

> Patches are now upstream:
>  https://github.com/open-power/petitboot/commit/057dce2dadee2e2
> (just mirror the @jk-ozlabs msg from internal commit/bugzillia) 

@klauskiwi would you help with creating this Petitboot PR and merge? 
I'm not 100% sure if all the updates are ready now...? just would like to track this item at one same place for Mihawk-LC. Please let us know if any actions needed from @chcyjoy (or myself). Thank you!

----------------------------------
# Mihawk FW Release Plan:
12/06 => 5th FW Release 
12/20 => 6th FW Release --> This release will be the GA1 candidate driver 1st (the cutoff date)

-Hank

**Comment by HankChang** [comment]
FYI - @chcyjoy @bwmashak @youhour
Update the status of the item (4). [Petitboot updates for OpenShift/RHEL8]  
From Jeremy's response today that the upstream op-build pull request is up: https://github.com/open-power/op-build/pull/3321

After the above PR is merged, Klaus will help us to merge/rebase it into release-op940 branch soon. 
-- 12/04 updated, draft PR for OP940 provided here - https://github.com/ibm-op-release/op-build/pull/676

Thanks,
-Hank

**Comment by HankChang** [comment]
FYI - @chcyjoy @bwmashak @youhour
Update the status of the item (4). [Petitboot updates for OpenShift/RHEL8] --> [Merged to OP940]
All updates were merged into "release-op940" and the 6th FW release (12/20) will include it.

Merged PR URL: https://github.com/ibm-op-release/op-build/pull/676

Thank you, @klauskiwi @jk-ozlabs 

-Hank

**Comment by hegdevasant** [comment]
https://github.com/ibm-op-release/op-build/pull/677 will address skiboot related changes.

-Vasant

**Comment by chcyjoy** [comment]
> #677 will address skiboot related changes.
> 
> -Vasant

Thanks for your help!!
-joy chu

**Comment by chcyjoy** [comment]
All merged so close this issue.
